Sprint 1
salnikovss/middle.messenger.praktikum.yandex pull request #1
Opened 2022-09-12 11:05 UTC by salnikovss

2022-09-12 18:06 UTC, podlovchenko requested changes
Привет) В целом все хорошо, но локально при переходе по ссылкам `Cannot GET /signin`, нужно поправить

2022-09-12 18:21 UTC, salnikovss commented on server.js
> +// });
Все верно. Но если ссылаться на dist папку, то тесты не проходят, т.к. в процессе теста не делается npm run build, делается только npm run start. 
Вижу решением только при npm run start делать build, о чем не подумал изначально. 
Поправлю

2022-09-12 18:45 UTC, salnikovss commented on server.js
> +const PORT = 3000;
Готово
```bash
export PORT=4000 && node server.js
Listening on port 4000!
```

2022-09-13 08:32 UTC, podlovchenko commented
Работу принимаю)

2022-09-13 13:06 UTC, merged